version: '3.9'

services:
    nginx:
        restart: unless-stopped
        image: staticfloat/nginx-certbot
        network_mode: host
        environment:
            CERTBOT_EMAIL: $CERTBOT_EMAIL
            ENVSUBST_VARS: SERVER_NAME CAPYLAND_TGB CAPYLAND_VSCODE TRADE_GUILD_TGB_MAIN TRADE_GUILD_TGB_TEST CAPYVALLEY_BORDER_PATROL_TGB
            # Змінні для шаблону
            SERVER_NAME: $SERVER_NAME
            CAPYLAND_TGB: $CAPYLAND_TGB
            CAPYLAND_VSCODE: $CAPYLAND_VSCODE
            TRADE_GUILD_TGB_MAIN: $TRADE_GUILD_TGB_MAIN
            TRADE_GUILD_TGB_TEST: $TRADE_GUILD_TGB_TEST
            CAPYVALLEY_BORDER_PATROL_TGB: $CAPYVALLEY_BORDER_PATROL_TGB
        volumes:
            - ./.docker/nginx/conf.d:/etc/nginx/user.conf.d:ro
            - ./html:/usr/share/nginx/html
            - letsencrypt:/etc/letsencrypt

volumes:
    letsencrypt:
