version: '3.9'

services:
    nginx:
        restart: unless-stopped
        image: staticfloat/nginx-certbot
        network_mode: host
        environment:
            CERTBOT_EMAIL: $CERTBOT_EMAIL
            ENVSUBST_VARS: SERVER_NAME CAPYLAND_TELEGRAM_BOT_PORT CAPYLAND_FAKE_PLAYERS_PORT SUBSCRIPTION_MANAGER_BOT_PORT
            # Змінні для щаблону
            SERVER_NAME: $SERVER_NAME
            CAPYLAND_TELEGRAM_BOT_PORT: $CAPYLAND_TELEGRAM_BOT_PORT
            CAPYLAND_FAKE_PLAYERS_PORT: $CAPYLAND_FAKE_PLAYERS_PORT
            SUBSCRIPTION_MANAGER_BOT_PORT: $SUBSCRIPTION_MANAGER_BOT_PORT
        volumes:
            - ./.docker/nginx/conf.d:/etc/nginx/user.conf.d:ro
            - ./html:/usr/share/nginx/html
            - letsencrypt:/etc/letsencrypt

volumes:
    letsencrypt:
