version: '3.9'

services:
    proxy:
        restart: unless-stopped
        image: jonasal/nginx-certbot
        network_mode: host
        environment:
            CERTBOT_EMAIL: $CERTBOT_EMAIL
            SERVER_NAME: $SERVER_NAME
        volumes:
            - ./templates:/etc/nginx/templates:ro
            - letsencrypt:/etc/letsencrypt

volumes:
    letsencrypt:
