FROM nginx:stable

ARG CERTBOT_EMAIL
ARG CERTBOT_DOMAIN_LIST

RUN apt-get update
RUN apt-get install -y cron certbot python3-certbot-nginx bash wget
RUN certbot certonly --standalone --agree-tos -m "${CERTBOT_EMAIL}" -n -d ${CERTBOT_DOMAIN_LIST}
RUN rm -rf /var/lib/apt/lists/*
RUN echo "PATH=$PATH" > /etc/cron.d/certbot-renew
RUN echo "@monthly certbot renew --nginx >> /var/log/cron.log 2>&1" >>/etc/cron.d/certbot-renew
RUN crontab /etc/cron.d/certbot-renew

VOLUME /etc/letsencrypt

CMD ["sh", "-c", "cron && nginx -g 'daemon off;'"]
